M48
; DRILL file {KiCad 8.0.2-8.0.2-0~ubuntu22.04.1} date 2024-06-03T16:53:45-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-06-03T16:53:45-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2-8.0.2-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
%
G90
G05
T1
X56.8Y-38.8
X56.8Y-69.2
X119.2Y-38.8
X119.2Y-69.2
M30
